#!/bin/sh

# SPLIT ########################################################################
python data_splits.py --data_directory /Users/felixkrones/python_projects/data/physionet_challenge_2022/physionet.org/files/circor-heart-sound/1.0.3/training_data --vali_size 0.2 --test_size 0.2 --cv True


# MULTICLASS MURMUR ############################################################
## Train
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_0/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_0/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_0 --model_dir data/c_models/cv_True_stratified_False/split_0
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_1/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_1/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_1 --model_dir data/c_models/cv_True_stratified_False/split_1
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_2/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_2/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_2 --model_dir data/c_models/cv_True_stratified_False/split_2
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_3/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_3/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_3 --model_dir data/c_models/cv_True_stratified_False/split_3
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_4/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_4/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_4 --model_dir data/c_models/cv_True_stratified_False/split_4
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_5/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_5/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_5 --model_dir data/c_models/cv_True_stratified_False/split_5
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_6/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_6/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_6 --model_dir data/c_models/cv_True_stratified_False/split_6
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_7/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_7/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_7 --model_dir data/c_models/cv_True_stratified_False/split_7
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_8/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_8/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_8 --model_dir data/c_models/cv_True_stratified_False/split_8
python train_resnet.py --recalc_features --model_label BinaryPresent --classes_name binary_present --train_data_directory data/a_splits/cv_True_stratified_False/split_9/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_9/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_9 --model_dir data/c_models/cv_True_stratified_False/split_9

python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_0/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_0/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_0 --model_dir data/c_models/cv_True_stratified_False/split_0
python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_1/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_1/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_1 --model_dir data/c_models/cv_True_stratified_False/split_1
python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_2/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_2/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_2 --model_dir data/c_models/cv_True_stratified_False/split_2
python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_3/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_3/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_3 --model_dir data/c_models/cv_True_stratified_False/split_3
python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_4/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_4/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_4 --model_dir data/c_models/cv_True_stratified_False/split_4
python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_5/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_5/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_5 --model_dir data/c_models/cv_True_stratified_False/split_5
python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_6/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_6/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_6 --model_dir data/c_models/cv_True_stratified_False/split_6
python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_7/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_7/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_7 --model_dir data/c_models/cv_True_stratified_False/split_7
python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_8/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_8/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_8 --model_dir data/c_models/cv_True_stratified_False/split_8
python train_resnet.py --recalc_features --model_label BinaryUnknown --classes_name binary_unknown --train_data_directory data/a_splits/cv_True_stratified_False/split_9/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_9/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_9 --model_dir data/c_models/cv_True_stratified_False/split_9

## Run and Evaluate
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_0/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_0 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_0/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_0/model_BinaryUnknown.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_1/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_1 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_1/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_1/model_BinaryUnknown.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_2/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_2 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_2/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_2/model_BinaryUnknown.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_3/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_3 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_3/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_3/model_BinaryUnknown.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_4/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_4 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_4/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_4/model_BinaryUnknown.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_5/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_5 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_5/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_5/model_BinaryUnknown.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_6/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_6 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_6/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_6/model_BinaryUnknown.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_7/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_7 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_7/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_7/model_BinaryUnknown.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_8/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_8 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_8/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_8/model_BinaryUnknown.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_9/test_data --output_directory data/d_dbres_multiclass_outputs/cv_True_stratified_False/split_9 --model_binary_present_pth data/c_models/cv_True_stratified_False/split_9/model_BinaryPresent.pth --model_binary_unknown_pth data/c_models/cv_True_stratified_False/split_9/model_BinaryUnknown.pth




# BINARY MURMUR ################################################################
## Train
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_0/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_0/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_0 --model_dir data/c_models/cv_True_stratified_False/split_0
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_1/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_1/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_1 --model_dir data/c_models/cv_True_stratified_False/split_1
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_2/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_2/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_2 --model_dir data/c_models/cv_True_stratified_False/split_2
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_3/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_3/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_3 --model_dir data/c_models/cv_True_stratified_False/split_3
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_4/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_4/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_4 --model_dir data/c_models/cv_True_stratified_False/split_4
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_5/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_5/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_5 --model_dir data/c_models/cv_True_stratified_False/split_5
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_6/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_6/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_6 --model_dir data/c_models/cv_True_stratified_False/split_6
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_7/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_7/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_7 --model_dir data/c_models/cv_True_stratified_False/split_7
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_8/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_8/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_8 --model_dir data/c_models/cv_True_stratified_False/split_8
python train_resnet.py --recalc_features --model_label MurmurBinary --classes_name murmur_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_9/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_9/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_9 --model_dir data/c_models/cv_True_stratified_False/split_9

## Run and Evaluate
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_0/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_0 --model_binary_pth data/c_models/cv_True_stratified_False/split_0/model_MurmurBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_1/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_1 --model_binary_pth data/c_models/cv_True_stratified_False/split_1/model_MurmurBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_2/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_2 --model_binary_pth data/c_models/cv_True_stratified_False/split_2/model_MurmurBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_3/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_3 --model_binary_pth data/c_models/cv_True_stratified_False/split_3/model_MurmurBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_4/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_4 --model_binary_pth data/c_models/cv_True_stratified_False/split_4/model_MurmurBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_5/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_5 --model_binary_pth data/c_models/cv_True_stratified_False/split_5/model_MurmurBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_6/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_6 --model_binary_pth data/c_models/cv_True_stratified_False/split_6/model_MurmurBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_7/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_7 --model_binary_pth data/c_models/cv_True_stratified_False/split_7/model_MurmurBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_8/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_8 --model_binary_pth data/c_models/cv_True_stratified_False/split_8/model_MurmurBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_9/test_data --output_directory data/d_dbres_MurmurBinary_outputs/cv_True_stratified_False/split_9 --model_binary_pth data/c_models/cv_True_stratified_False/split_9/model_MurmurBinary.pth

## Run XGBooost models
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_0/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_0/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_0/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_0/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_0
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_1/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_1/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_1/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_1/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_1
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_2/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_2/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_2/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_2/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_2
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_3/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_3/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_3/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_3/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_3
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_4/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_4/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_4/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_4/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_4
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_5/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_5/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_5/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_5/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_5
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_6/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_6/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_6/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_6/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_6
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_7/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_7/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_7/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_7/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_7
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_8/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_8/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_8/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_8/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_8
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_9/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_9/test_data --dbres_output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_9/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_9/model_MurmurBinary.pth --output_directory data/d_xgboost_MurmurBinary_outputs/cv_True_stratified_False/split_9




# BINARY OUTCOME ###############################################################
## Train
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_0/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_0/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_0 --model_dir data/c_models/cv_True_stratified_False/split_0
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_1/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_1/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_1 --model_dir data/c_models/cv_True_stratified_False/split_1
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_2/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_2/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_2 --model_dir data/c_models/cv_True_stratified_False/split_2
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_3/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_3/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_3 --model_dir data/c_models/cv_True_stratified_False/split_3
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_4/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_4/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_4 --model_dir data/c_models/cv_True_stratified_False/split_4
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_5/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_5/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_5 --model_dir data/c_models/cv_True_stratified_False/split_5
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_6/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_6/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_6 --model_dir data/c_models/cv_True_stratified_False/split_6
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_7/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_7/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_7 --model_dir data/c_models/cv_True_stratified_False/split_7
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_8/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_8/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_8 --model_dir data/c_models/cv_True_stratified_False/split_8
python train_resnet.py --recalc_features --model_label OutcomeBinary --classes_name outcome_binary --train_data_directory data/a_splits/cv_True_stratified_False/split_9/train_data --vali_data_directory data/a_splits/cv_True_stratified_False/split_9/vali_data --spectrogram_directory data/b_spectrograms/cv_True_stratified_False/split_9 --model_dir data/c_models/cv_True_stratified_False/split_9

## Run and Evaluate
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_0/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_0 --model_binary_pth data/c_models/cv_True_stratified_False/split_0/model_OutcomeBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_1/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_1 --model_binary_pth data/c_models/cv_True_stratified_False/split_1/model_OutcomeBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_2/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_2 --model_binary_pth data/c_models/cv_True_stratified_False/split_2/model_OutcomeBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_3/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_3 --model_binary_pth data/c_models/cv_True_stratified_False/split_3/model_OutcomeBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_4/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_4 --model_binary_pth data/c_models/cv_True_stratified_False/split_4/model_OutcomeBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_5/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_5 --model_binary_pth data/c_models/cv_True_stratified_False/split_5/model_OutcomeBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_6/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_6 --model_binary_pth data/c_models/cv_True_stratified_False/split_6/model_OutcomeBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_7/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_7 --model_binary_pth data/c_models/cv_True_stratified_False/split_7/model_OutcomeBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_8/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_8 --model_binary_pth data/c_models/cv_True_stratified_False/split_8/model_OutcomeBinary.pth
python dbres.py --recalc_output --data_directory data/a_splits/cv_True_stratified_False/split_9/test_data --output_directory data/d_dbres_OutcomeBinary_outputs/cv_True_stratified_False/split_9 --model_binary_pth data/c_models/cv_True_stratified_False/split_9/model_OutcomeBinary.pth

## Run XGBoooost models
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_0/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_0/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_0/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_0/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_0
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_1/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_1/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_1/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_1/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_1
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_2/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_2/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_2/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_2/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_2
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_3/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_3/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_3/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_3/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_3
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_4/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_4/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_4/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_4/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_4
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_5/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_5/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_5/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_5/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_5
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_6/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_6/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_6/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_6/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_6
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_7/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_7/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_7/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_7/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_7
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_8/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_8/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_8/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_8/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_8
python xgboost_integration.py --train_data_directory data/a_splits/cv_True_stratified_False/split_9/train_data --test_data_directory data/a_splits/cv_True_stratified_False/split_9/test_data --dbres_output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_9/dbres_output --model_binary_pth data/c_models/cv_True_stratified_False/split_9/model_OutcomeBinary.pth --output_directory data/d_xgboost_OutcomeBinary_outputs/cv_True_stratified_False/split_9



# EVALUATE OUTCOME ON 2016 #####################################################
python dbres.py --recalc_output --recordings_file data/e_challenge_anaylsis/2016_challenge_annotations.csv --output_directory data/f_pyc2016/dbres_outputs --model_binary_pth data/c_models/cv_True_stratified_False/split_0/model_OutcomeBinary.pth 
